"""Explicit qutrit Kraus channels under the frozen |0>, |1>, |2> basis."""

from __future__ import annotations

import math

import numpy as np

from core.cptp import KrausChannel, KrausMap
from core.gates import Matrix


QUTRIT_DIMENSION = 3
QUTRIT_DEPHASING_CONVENTION = "number_operator_adjacent_factor_v1"
QUTRIT_LEAKAGE_EVENT = "incoherent_1_to_2_event_v1"


def qutrit_downward_transition_channel(
    upper_level: int,
    transition_probability: float,
) -> KrausChannel:
    """Return the adjacent downward channel 1->0 or 2->1."""

    upper = _level(upper_level, "upper_level")
    if upper not in (1, 2):
        raise ValueError("upper_level must be 1 or 2")
    return _transition_channel(
        source_level=upper,
        target_level=upper - 1,
        transition_probability=transition_probability,
        name=f"qutrit_transition_{upper}{upper - 1}_down",
    )


def qutrit_upward_transition_channel(
    lower_level: int,
    transition_probability: float,
) -> KrausChannel:
    """Return the adjacent upward channel 0->1 or 1->2."""

    lower = _level(lower_level, "lower_level")
    if lower not in (0, 1):
        raise ValueError("lower_level must be 0 or 1")
    return _transition_channel(
        source_level=lower,
        target_level=lower + 1,
        transition_probability=transition_probability,
        name=f"qutrit_transition_{lower}{lower + 1}_up",
    )


def qutrit_number_dephasing_channel(
    adjacent_coherence_factor: float,
) -> KrausChannel:
    """Return qutrit number-operator dephasing as an explicit channel.

    If adjacent coherences are multiplied by ``eta``, rho_02 is multiplied by
    ``eta**4``. This matches the frozen number-operator dephasing relation.
    """

    eta = _probability(
        adjacent_coherence_factor,
        "adjacent_coherence_factor",
    )
    correlation = np.asarray(
        (
            (1.0, eta, eta**4),
            (eta, 1.0, eta),
            (eta**4, eta, 1.0),
        ),
        dtype=np.complex128,
    )
    eigenvalues, eigenvectors = np.linalg.eigh(correlation)
    if float(np.min(eigenvalues)) < -1e-12:
        raise RuntimeError("qutrit dephasing correlation matrix is not PSD")

    operators: list[Matrix] = []
    for index, eigenvalue in enumerate(eigenvalues):
        clipped = max(0.0, float(eigenvalue))
        if clipped <= 1e-15:
            continue
        diagonal = math.sqrt(clipped) * eigenvectors[:, index]
        operator = np.diag(diagonal.astype(np.complex128))
        operators.append(_to_matrix(operator))

    return KrausChannel(
        name="qutrit_number_dephasing",
        operators=tuple(operators),
    )


def qutrit_leakage_channel(
    leakage_probability: float,
) -> KrausChannel:
    """Return an explicit incoherent |1> to |2> leakage event.

    This discrete channel is not the coherent leakage generated by the qutrit
    pulse Hamiltonian and is not added implicitly to continuous evolution.
    """

    return _transition_channel(
        source_level=1,
        target_level=2,
        transition_probability=leakage_probability,
        name="qutrit_incoherent_leakage_1_to_2",
    )


def qutrit_computational_measurement_channel() -> KrausChannel:
    """Return full |0>, |1>, |2> measurement with outcomes discarded."""

    outcome_maps = qutrit_computational_measurement_instrument()
    return KrausChannel(
        name="qutrit_computational_measurement_discarded",
        operators=tuple(
            outcome_map.operators[0] for outcome_map in outcome_maps
        ),
    )


def qutrit_computational_measurement_instrument(
) -> tuple[KrausMap, KrausMap, KrausMap]:
    """Return three CP trace-nonincreasing computational outcome maps."""

    return tuple(
        KrausMap(
            name=f"qutrit_computational_measurement_outcome_{level}",
            operators=(_projector(level),),
        )
        for level in range(QUTRIT_DIMENSION)
    )


def _transition_channel(
    *,
    source_level: int,
    target_level: int,
    transition_probability: float,
    name: str,
) -> KrausChannel:
    probability = _probability(
        transition_probability,
        "transition_probability",
    )
    no_jump = np.eye(QUTRIT_DIMENSION, dtype=np.complex128)
    no_jump[source_level, source_level] = math.sqrt(1.0 - probability)
    jump = np.zeros(
        (QUTRIT_DIMENSION, QUTRIT_DIMENSION),
        dtype=np.complex128,
    )
    jump[target_level, source_level] = math.sqrt(probability)
    return KrausChannel(
        name=name,
        operators=(_to_matrix(no_jump), _to_matrix(jump)),
    )


def _projector(level: int) -> Matrix:
    projector = np.zeros(
        (QUTRIT_DIMENSION, QUTRIT_DIMENSION),
        dtype=np.complex128,
    )
    projector[level, level] = 1.0
    return _to_matrix(projector)


def _to_matrix(array: np.ndarray) -> Matrix:
    return tuple(
        tuple(complex(value) for value in row)
        for row in array
    )


def _level(value: int, field_name: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"{field_name} must be an integer qutrit level")
    if value < 0 or value >= QUTRIT_DIMENSION:
        raise ValueError(f"{field_name} must be within [0, 2]")
    return value


def _probability(value: float, field_name: str) -> float:
    converted = float(value)
    if (
        not math.isfinite(converted)
        or converted < 0.0
        or converted > 1.0
    ):
        raise ValueError(f"{field_name} must be finite and within [0, 1]")
    return converted
