from __future__ import annotations

import streamlit as st

from core.capabilities import (
    DEFAULT_SIMULATION_MODEL,
    GATE_AWARE_HAMILTONIAN_LINDBLAD_MODEL,
    GATE_AWARE_SPLIT_STEP_MODEL,
    POST_CIRCUIT_DEGRADATION_MODEL,
)
from core.physical_environment import (
    INPUT_MODE_NORMALIZED,
    INPUT_MODE_PHYSICAL,
    baseline_profile_noise_info,
    compute_environment_rates,
    device_quality_mapping_info,
)
from core.results import EnvironmentConfig


LOW_NOISE = {
    "temperature": 0.1,
    "magnetic_field": 0.1,
    "noise_level": 0.1,
}
HIGH_NOISE = {
    "temperature": 0.8,
    "magnetic_field": 0.1,
    "noise_level": 0.8,
}


def render_environment_panel(expert: bool = False) -> dict[str, float]:
    st.subheader("Environment")

    if expert:
        input_mode = _render_input_mode_selector()
    else:
        input_mode = INPUT_MODE_NORMALIZED
        st.session_state["environment_input_mode"] = INPUT_MODE_NORMALIZED

    if input_mode == INPUT_MODE_PHYSICAL:
        environment_values = _render_physical_controls()
    else:
        environment_values = _render_normalized_controls()

    if expert:
        _render_derived_rates()

    _render_simulation_settings(expert=expert)

    if input_mode == INPUT_MODE_NORMALIZED:
        st.caption(
            "These are normalized parameters for learning, not exact hardware "
            "temperature, magnetic field, or material values."
        )
    else:
        st.caption(
            "Physical-unit inputs use a generic transmon-inspired educational "
            "profile, not strict hardware calibration."
        )

    return environment_values


def _render_normalized_controls() -> dict[str, float]:
    first, second = st.columns(2)
    if first.button("Low noise", use_container_width=True):
        _apply_preset(LOW_NOISE)
    if second.button("High noise", use_container_width=True):
        _apply_preset(HIGH_NOISE)

    temperature = st.slider(
        "Temperature parameter",
        min_value=0.0,
        max_value=1.0,
        value=float(st.session_state.get("temperature", 0.1)),
        step=0.01,
        key="temperature",
    )
    flux_noise = st.slider(
        "Flux noise parameter",
        min_value=0.0,
        max_value=1.0,
        value=float(st.session_state.get("magnetic_field", 0.1)),
        step=0.01,
        key="magnetic_field",
    )
    noise_level = st.slider(
        "Noise level",
        min_value=0.0,
        max_value=1.0,
        value=float(st.session_state.get("noise_level", 0.1)),
        step=0.01,
        key="noise_level",
    )

    return {
        "temperature": temperature,
        "magnetic_field": flux_noise,
        "noise_level": noise_level,
    }


def _render_simulation_settings(expert: bool = False) -> None:
    with st.expander("Simulation settings", expanded=False):
        st.number_input(
            "Duration (us)",
            min_value=0.001,
            value=float(st.session_state.get("duration_us", 20.0)),
            step=1.0,
            key="duration_us",
        )
        st.number_input(
            "Time steps",
            min_value=2,
            value=int(st.session_state.get("time_steps", 101)),
            step=1,
            key="time_steps",
        )
        st.slider(
            "Fidelity threshold",
            min_value=0.0,
            max_value=1.0,
            value=float(st.session_state.get("fidelity_threshold", 0.9)),
            step=0.01,
            key="fidelity_threshold",
        )
        options = (
            [
                DEFAULT_SIMULATION_MODEL,
                GATE_AWARE_HAMILTONIAN_LINDBLAD_MODEL,
                POST_CIRCUIT_DEGRADATION_MODEL,
                GATE_AWARE_SPLIT_STEP_MODEL,
            ]
            if expert
            else [DEFAULT_SIMULATION_MODEL]
        )
        current = st.session_state.get("model", DEFAULT_SIMULATION_MODEL)
        st.selectbox(
            "Simulation model",
            options=options,
            index=options.index(current) if current in options else 0,
            key="model",
            format_func=_format_simulation_model,
        )
        st.caption(
            "The standard model is gate-aware: gates are generated by effective "
            "Hamiltonians while Lindblad noise acts during gate execution. "
            "Post-circuit degradation is retained only for legacy comparison."
        )


def _render_input_mode_selector() -> str:
    st.caption("Expert environment input")
    options = [
        INPUT_MODE_NORMALIZED,
        INPUT_MODE_PHYSICAL,
    ]
    current = st.session_state.get("environment_input_mode", INPUT_MODE_NORMALIZED)
    return st.selectbox(
        "Environment input mode",
        options=options,
        index=options.index(current) if current in options else 0,
        format_func=lambda value: {
            INPUT_MODE_NORMALIZED: "Simple normalized controls",
            INPUT_MODE_PHYSICAL: "Expert physical units",
        }[value],
        key="environment_input_mode",
    )


def _render_physical_controls() -> dict[str, float]:
    st.warning(
        "This is a generic transmon-inspired educational model, not a "
        "strictly calibrated hardware profile."
    )
    if st.button("Ideal reference / Noiseless", use_container_width=True):
        st.session_state["ideal_reference"] = True
        st.session_state["device_quality"] = 1.0
        st.session_state["temperature_mk"] = 0.0
        st.session_state["flux_noise_phi0"] = 0.0
    st.caption(
        "Ideal reference / Noiseless is a comparison reference with zero "
        "environment rates, not a physical hardware profile."
    )
    st.checkbox(
        "Use ideal reference rates",
        value=bool(st.session_state.get("ideal_reference", False)),
        key="ideal_reference",
        help=(
            "Sets gamma_down, gamma_up, and gamma_phi to zero for comparison. "
            "This bypasses the finite coherence limits of the device profile."
        ),
    )
    st.slider(
        "Device Quality (0 = profile minimum, 1 = profile maximum)",
        min_value=0.0,
        max_value=1.0,
        value=float(st.session_state.get("device_quality", 0.5)),
        step=0.01,
        key="device_quality",
    )
    st.caption(
        "Device Quality interpolates between the profile minimum and maximum. "
        "Device Quality = 1.0 means the maximum coherence time of the selected "
        "profile, not a noiseless device. Device Quality = 0.0 means the "
        "minimum coherence time."
    )
    st.number_input(
        "Temperature [mK]",
        min_value=0.0,
        value=float(st.session_state.get("temperature_mk", 15.0)),
        step=1.0,
        key="temperature_mk",
    )
    st.number_input(
        "Flux Noise Amplitude [Phi0]",
        min_value=0.0,
        value=float(st.session_state.get("flux_noise_phi0", 1e-6)),
        step=1e-6,
        format="%.2e",
        key="flux_noise_phi0",
    )
    with st.expander("Advanced physical inputs", expanded=False):
        st.number_input(
            "Qubit Frequency [GHz]",
            min_value=0.001,
            value=float(st.session_state.get("qubit_frequency_ghz", 5.0)),
            step=0.1,
            key="qubit_frequency_ghz",
        )
        st.number_input(
            "T1 max [us]",
            min_value=0.001,
            value=float(st.session_state.get("t1_max_us", 100.0)),
            step=10.0,
            key="t1_max_us",
        )
        st.number_input(
            "Tphi max [us]",
            min_value=0.001,
            value=float(st.session_state.get("tphi_max_us", 100.0)),
            step=10.0,
            key="tphi_max_us",
        )

    return {
        "temperature": st.session_state.get("temperature", 0.1),
        "magnetic_field": st.session_state.get("magnetic_field", 0.1),
        "noise_level": st.session_state.get("noise_level", 0.1),
    }


def _render_derived_rates() -> None:
    rates = compute_environment_rates(
        EnvironmentConfig(
            input_mode=st.session_state.get(
                "environment_input_mode",
                INPUT_MODE_NORMALIZED,
            ),
            temperature=st.session_state.get("temperature", 0.1),
            magnetic_field=st.session_state.get("magnetic_field", 0.1),
            noise_level=st.session_state.get("noise_level", 0.1),
            device_quality=st.session_state.get("device_quality", 0.5),
            temperature_mk=st.session_state.get("temperature_mk", 15.0),
            flux_noise_phi0=st.session_state.get("flux_noise_phi0", 1e-6),
            qubit_frequency_ghz=st.session_state.get("qubit_frequency_ghz", 5.0),
            t1_max_us=st.session_state.get("t1_max_us", 100.0),
            tphi_max_us=st.session_state.get("tphi_max_us", 100.0),
            ideal_reference=st.session_state.get("ideal_reference", False),
        )
    )
    with st.expander("Derived physical quantities", expanded=True):
        first, second = st.columns(2)
        first.metric("n_th", _format_value(rates.n_th))
        second.metric("T1_base [us]", _format_value(rates.t1_base_us))
        first.metric("Tphi_base [us]", _format_value(rates.tphi_base_us))
        second.metric("gamma_down [1/us]", _format_value(rates.gamma_down_per_us))
        first.metric("gamma_up [1/us]", _format_value(rates.gamma_up_per_us))
        second.metric("gamma_phi [1/us]", _format_value(rates.gamma_phi_per_us))
        first.metric("T1_effective [us]", _format_value(rates.t1_effective_us))
        second.metric("T2_effective [us]", _format_value(rates.t2_effective_us))
        if rates.ideal_reference:
            st.info(
                "Ideal reference is active: gamma_down, gamma_up, and gamma_phi "
                "are set to zero for comparison."
            )
        else:
            baseline_info = baseline_profile_noise_info(rates)
            if baseline_info:
                st.info(baseline_info)
            quality_info = device_quality_mapping_info(rates)
            if quality_info:
                st.info(quality_info)
        st.caption(
            "T1_base/Tphi_base are interpolated between profile minima and "
            "maxima. Use Ideal reference / Noiseless for zero-rate comparison."
        )
        st.caption(
            "Real device parameters fluctuate over time and across chips; this "
            "profile is for interpretable exploration, not calibration."
        )


def _apply_preset(values: dict[str, float]) -> None:
    for key, value in values.items():
        st.session_state[key] = value


def _format_value(value: float | None) -> str:
    if value is None:
        return "not available"
    if abs(value) >= 1e4 or (abs(value) < 1e-3 and value != 0.0):
        return f"{value:.3e}"
    return f"{value:.4g}"


def _format_simulation_model(model: str) -> str:
    labels = {
        DEFAULT_SIMULATION_MODEL: "Standard gate-aware Lindblad",
        GATE_AWARE_HAMILTONIAN_LINDBLAD_MODEL: (
            "Gate-aware effective-Hamiltonian Lindblad"
        ),
        POST_CIRCUIT_DEGRADATION_MODEL: "Legacy post-circuit degradation",
        GATE_AWARE_SPLIT_STEP_MODEL: "Gate-aware split-step fallback",
    }
    return labels.get(model, model)
