[package]
name = "yuragi_strider_rust"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "yuragi_strider_rust"
crate-type = ["cdylib"]

[dependencies]
gemm = { version = "0.19.0", default-features = false, features = ["std", "rayon"] }
pyo3 = "0.29.0"
